# How many distinct terms are in the sequence 
# generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
def compute():
    c = set()
    for a in range(2, 101):
        for b in range(2, 101):
            c.add(a**b)
    return len(c)

if __name__ =='__main__':
    print(compute())